events {}
http {
    upstream backend {
        server host.docker.internal:5001;
        server host.docker.internal:5002;
        server host.docker.internal:5003;
        server host.docker.internal:5004;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://backend;
        }
    }
}