- name: Install Grafana Repo
  copy:
    dest: /etc/yum.repos.d/grafana.repo
    content: |
      [grafana]
      name=Grafana
      enabled=1
      baseurl=https://packages.grafana.com/oss/rpm
      repo_gpgcheck=1
      gpgcheck=1
      gpgkey=https://packages.grafana.com/gpg.key


- name: Install Grafana
  yum:
    name: grafana
    state: present


- name: Start Grafana
  systemd:
    name: grafana-server
    state: started
    enabled: yes


- name: Create datasource provisioning directory
  file:
    path: /etc/grafana/provisioning/datasources
    state: directory
    group: root
    owner: root
    mode: '0755'


- name: Copy Prometheus datasource configuration
  copy:
    src: datasources.yml
    dest: /etc/grafana/provisioning/datasources/datasources.yml
    owner: root
    group: root
    mode: '0644'


- name: Restart Grafana to apply datasource
  systemd:
    name: grafana-server
    state: restarted


- name: Grafana Health check
  uri:
    url: http://localhost:3000/api/health
    status_code: 200
    method: GET
  register: grafana_health
  retries: 15
  delay: 5
  until: grafana_health.status == 200


- name: Create dashboard provisioning directory
  file:
    path: /etc/grafana/provisioning/dashboards
    state: directory


- name: Copy dashboard provider configuration
  copy:
    src: dashboards.yml
    dest: /etc/grafana/provisioning/dashboards/dashboards.yml


- name: Copy Static Dashboards
  copy:
    src: dashboards/static/
    dest: /etc/grafana/provisioning/dashboards/


- name: Render ECS Dashboard
  template:
    src: dashboards/templates/ecs.json.j2
    dest: /etc/grafana/provisioning/dashboards/ecs.json


- name: Render ALB Dashboard
  template:
    src: dashboards/templates/alb.json.j2
    dest: /etc/grafana/provisioning/dashboards/alb.json


- name: Render RDS Dashboard
  template:
    src: dashboards/templates/rds.json.j2
    dest: /etc/grafana/provisioning/dashboards/rds.json


- name: Restart Grafana
  systemd:
    name: grafana-server
    state: restarted