networks:
  ecomm-app-network:
    driver: bridge
    external: true

services:
  app-prod-blue:
    image: ${IMAGE}
    container_name: app-prod
    environment:
      ENV: production
    env_file:
      - ./.env.prod
    expose:
      - "5000"
    networks:
      - ecomm-app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 8s
      retries: 10
      start_period: 90s


volumes:
  jenkins_main:


