networks:
  ecomm-app-network:
    driver: bridge
    external: true

services:
  app-dev:
    image: ${IMAGE}
    container_name: app-dev
    ports:
      - "5001:5000"
    networks:
      - ecomm-app-network
    environment:
      ENV: development
      VERSION: $IMG_TAG}
    env_file:
      - ./.env.dev