- name: Setup Prometheus & Grafana
  hosts: monitoring-server
  become: yes

  roles:
    - prometheus
    - grafana
    - node_exporter
    - cloudwatch_exporter


  vars_files:
    -../../terraform/terraform_outputs.json