- name: Install dependencies
  yum:
    name:
      - tar
      - wget
    state: present


- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/latest/download/prometheus-2.48.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz


- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes


- name: Create Symlink
  file:
    src:  /opt/prometheus-2.48.0.linux-amd64
    dest: /opt/prometheus
    state: link


- name: Copy Prometheus Configuration file
  copy:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml
  notify: Restart Prometheus


- name: Start Prometheus
  shell: >
    pgrep prometheus || nohup /opt/prometheus/prometheus \
      --config.file=/opt/prometheus/prometheus.yml \
      --web.listen-address="0.0.0.0:9090" &


- name: Prometheus Health check
  uri:
    url: http://localhost:9090/-/healthy
    method: GET
    status_code: 200
  register: prometheus_health
  retries: 15
  delay: 3
  until: prometheus_health.status == 200

